apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecommerce_ritz_ui
  description: Frontend Angular application for Ecommerce Ritz
spec:
  type: website
  lifecycle: production
  owner: ritesh.crazy04@gmail.com
  system: ecommerce-ritz
